#!/bin/sh
echo "🔍 Running pre-commit checks (lint & typecheck)..."
(cd backend && bunx --bun eslint . --ext ts --report-unused-disable-directives --max-warnings 0 && bun run build) && (cd frontend && bun run build)
