#!/bin/sh
echo "🚀 Running pre-push checks (lint, build & tests)..."
(cd backend && bunx --bun eslint . --ext ts --report-unused-disable-directives --max-warnings 0 && bun run build && bun run test) && (cd frontend && bun run build && bun run test)
